### ISSUE TITLE
some project URL are missing scheme, leading to 404

### ISSUE THREAD

**Issue by mnalis** [taginfo/taginfo-projects#157]
e.g. https://taginfo.openstreetmap.org/projects/wanderreitkarte#overview lists:

> Project URL: www.wanderreitkarte.de

instead of:
> Project URL: http://www.wanderreitkarte.de

so clicking on it leads to non-existent https://taginfo.openstreetmap.org/projects/www.wanderreitkarte.de

(there might be others too, I haven't checked - this is just an example one that is broken)

It should either:
- be enforced, so `scheme:` part of [URL](https://en.wikipedia.org/wiki/URL) must always be provided,
- or taginfo web should be changed so it detects missing schema and prepends `http://`

**Comment by joto** [comment]
I have told the project contact to correct their URL and opened an issue on taginfo/taginfo#415.
