### ISSUE TITLE
OpenAdvertMap has incorrect JSON

### ISSUE THREAD

**Issue by rugk** [taginfo/taginfo-projects#48]
It does not use the non-existent "Key:advertisment" (only), but the real `Key:advertising`.

**Comment by joto** [comment]
Please tell them, we here can't do anything about this.

**Comment by rugk** [comment]
But who is them? This txt only referrers some random server?

And why don't you just maintain all JSONs in a single repo so everyone can send PRs? I am sorry, but I cannot send a PR to that website.

**Comment by ImreSamu** [comment]
@rugk 
>But who is them? This txt only referrers some random server?

`OpenAdvertMap` 
*  https://github.com/PanierAvide/panieravide.github.io/blob/master/openadvertmap/taginfo.json

**Comment by rugk** [comment]
Great, thanks.
