### ISSUE TITLE
Clarify whose contact_name/contact_email

### ISSUE THREAD

**Issue by goldfndr** [taginfo/taginfo-projects#50]
For [the StreetComplete project/app](https://github.com/westnordost/StreetComplete), I've volunteered to create and maintain [a taginfo project file](https://github.com/goldfndr/StreetCompleteJSON) corresponding to said project. So there are two different people with different maintenance requirements.

As noted at goldfndr/StreetCompleteJSON#4, the project file description is somewhat ambiguous. I'm guessing it'd be me, as the https://taginfo.openstreetmap.org/projects/___ overview doesn't include a row or two for contact information. But I don't really know for sure.

Please let us know which you prefer. Thanks.

**Comment by joto** [comment]
It should be whoever is responsible for the JSON file. If there is a problem with the JSON file, this is the person who will be contacted.
