### ISSUE TITLE
OpenVegeMap isn't displayed for shop=* within shop=bakery

### ISSUE THREAD

**Issue by goldfndr** [taginfo/taginfo-projects#81]
https://taginfo.openstreetmap.org/keys/shop#projects includes OpenVegeMap.

https://taginfo.openstreetmap.org/tags/shop=bakery#projects includes OpenVegeMap in the shop=bakery portion (last pages) but not in the shop=* portion (should be fourth row).

**Comment by joto** [comment]
Not sure what you are trying to say here. OpenVegeMap has two entries for shop:

* `shop=*`
* `shop=bakery`

So it shows up on the `keys/shop` page and an the `tags/shop=bakery` page. So far so good.

If I understand correctly, you expect there to be an entry `shop=*` on the `tags/shop=bakery` page also, but there is a specific `shop=bakery` entry which beats the more generic one. So this is all correct. If you go to, say, https://taginfo.openstreetmap.org/tags/shop=knitting#projects , you'll see that OpenVegeMap shows up again with its generic `shop=*` entry.

Presumably if you have a specific tag in your projects file, this is more important than a generic key only. So this behaviour makes sense.

**Comment by goldfndr** [comment]
Thank you for the clarification, that a specific tag beats (filters out the display of) all generic key entries, even if their descriptions don't match.
